"use client";

import { useState } from "react";

export default function Home() {
  const [niche, setNiche] = useState("");
    const [ideas, setIdeas] = useState<string[]>([]);
      const [loading, setLoading] = useState(false);

        async function generateIdeas() {
            setLoading(true);

                const res = await fetch("/api/generate", {
                      method: "POST",
                            headers: {
                                    "Content-Type": "application/json",
                                          },
                                                body: JSON.stringify({ niche }),
                                                    });

                                                        const data = await res.json();
                                                            setIdeas(data.ideas || []);
                                                                setLoading(false);
                                                                  }

                                                                    return (
                                                                        <main
                                                                              className="w-full p-4 rounded-xl bg-gray-800 border border-gray-700 text-white outline-none focus:border-blue-500"
                                                                                                                        >
                                                                                                                              

                                            <h1
                                              style={{
                                                  fontSize: "3rem",
                                                      textAlign: "center",
                                                          color: "#ffffff",
                                                              marginBottom: "10px",
                                                                  fontWeight: "bold",
                                                                    }}
                                                                    >
                                                                    🚀 Social Fast Agent
                                                                    </h1>
                                                                    
                                                                    <p
                                                                      style={{
                                                                          textAlign: "center",
                                                                              color: "#94a3b8",
                                                                                  fontSize: "18px",
                                                                                      marginBottom: "35px",
                                                                                          lineHeight: "1.7",
                                                                                            }}
                                                                                            >
                                                                                            Create viral content ideas, captions, scripts and marketing campaigns with AI.
                                                                                            </p>                                                                                        <p>Create viral content ideas with AI.</p>

                                                                                                                                          <input
                                                                                                                                                  value={niche}
                                                                                                                                                          onChange={(e) => setNiche(e.target.value)}
                                                                                                                                                                  placeholder="Enter your niche..."
                                                                                                                                                                          style={{
                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                              padding: "14px",
                                                                                                                                                                                                        fontSize: "18px",
                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                            marginTop: "20px",
                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                  className="w-full mt-6 p-4 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 transition-all duration-300 font-bold text-lg shadow-lg"
                                                                                                                                                                                                                                                    onClick={generateIdeas}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                     {loading ? "🚀 Generating Viral Ideas..." : "🚀 Generate Ideas"}                                                                             
                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                              {ideas.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: "30px" }}>
                                                                                                                                                                                                                                                                                                                                                                                <h2>🔥 Viral Ideas</h2>

                                                                                                                                                                                                                                                                                                                                                                                          {ideas.map((idea, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                      key={index}
                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                background: "#1e293b",
                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #334155",
                                                                                                                                                                                                                                                                                                                                                                                                                                              boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3
                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#60a5fa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Idea {index + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#f8fafc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lineHeight: "1.6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {idea}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }