"use client";

import { useState } from "react";

export default function Home() {
  const [niche, setNiche] = useState("");
    const [ideas, setIdeas] = useState<string[]>([]);
      const [loading, setLoading] = useState(false);

        async function generateIdeas() {
            setLoading(true);

                const res = await fetch("/api/generate", {
                      method: "POST",
                            headers: {
                                    "Content-Type": "application/json",
                                          },
                                                body: JSON.stringify({ niche }),
                                                    });

                                                        const data = await res.json();
                                                            setIdeas(data.ideas || []);
                                                                setLoading(false);
                                                                  }

                                                                    return (
                                                                        <main
                                                                              className="w-full p-4 rounded-xl bg-gray-800 border border-gray-700 text-white outline-none focus:border-blue-500"
                                                                                                                        >
                                                                                                                              <h1 className="text-4xl font-extrabold text-center mb-2">
                                                                                                                                🚀 Social Fast Agent
                                                                                                                                </h1>

                                                                                                                                <p className="text-center text-gray-400 mb-8">
                                                                                                                                Generate viral content ideas in seconds with AI.
                                                                                                                                </p>

                                                                                                                                    <p>Create viral content ideas with AI.</p>

                                                                                                                                          <input
                                                                                                                                                  value={niche}
                                                                                                                                                          onChange={(e) => setNiche(e.target.value)}
                                                                                                                                                                  placeholder="Enter your niche..."
                                                                                                                                                                          style={{
                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                              padding: "14px",
                                                                                                                                                                                                        fontSize: "18px",
                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                            marginTop: "20px",
                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                  className="w-full mt-4 p-4 rounded-xl bg-blue-600 hover:bg-blue-700 transition font-bold"
                                                                                                                                                                                                                                                    onClick={generateIdeas}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                  {loading ? "Generating..." : "Generate Ideas"}
                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                              {ideas.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: "30px" }}>
                                                                                                                                                                                                                                                                                                                                                                                <h2>🔥 Viral Ideas</h2>

                                                                                                                                                                                                                                                                                                                                                                                          {ideas.map((idea, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                      key={index}
                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                background: "#1e293b",
                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #334155",
                                                                                                                                                                                                                                                                                                                                                                                                                                              boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3
                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#60a5fa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Idea {index + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#f8fafc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lineHeight: "1.6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {idea}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }